# Generated by Django 6.1.1 on 2026-10-05 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_rename_skills_profile_profession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_score', models.IntegerField(default=0, help_text='0-100')),
                ('engagement_score', models.IntegerField(default=0, help_text='0-100')),
                ('media_presence_score', models.IntegerField(default=0, help_text='0-100')),
                ('achievements_score', models.IntegerField(default=0, help_text='0-100')),
                ('projects_score', models.IntegerField(default=0, help_text='0-100')),
                ('activity_score', models.IntegerField(default=0, help_text='0-100')),
                ('impact_score', models.IntegerField(default=0, help_text='0-100')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_metrics', to='profiles.profile')),
            ],
        ),
    ]
